project:
  type: website
  output-dir: docs


website:
  sidebar:
    style: "floating"
  repo-url: https://github.com/edgar-treischl/daf
  title: "Deutsch als Fremdsprache"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dll2.qmd
        text: "DLL 2"

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    include-in-header: 
      - progress-bar.html
    lightbox: auto
    page-layout: article



