project:
  type: website
  output-dir: docs


website:
  sidebar:
    style: "floating"
  repo-url: https://github.com/edgar-treischl/daf
  title: "Deutsch als Fremdsprache"
  navbar:
    left:
      - text: "DLL 2"
        menu:
          - text: "01/02 Wie lernt man eigentlich Fremdsprachen?"
            href: dll22.qmd
          - text: "03 Wie lernt man Sprachen zu lernen?"
            href: dll23.qmd
          - text: "04 Wie helfen andere Sprachen beim Deutschlernen?"
            href: dll24.qmd
    

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    include-in-header: 
      - progress-bar.html
    lightbox: auto
    page-layout: article



